version: '3.7'
services:

  fullstack-oatuh-postgres:
    image: postgres:latest
    container_name: full_db_oauth_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./internal/migrations/000001_create_table_users.up.sql:/docker-entrypoint-initdb.d/create_tables.sql

    networks:
      - fullstackNetwork
  # app:
  #   container_name: full_app_oauth
  #   build: .
  #   ports:
  #     - 8080:8080
  #   restart: on-failure
  #   volumes:
  #     - api:/usr/src/app/
  #   depends_on:
  #     - fullstack-oatuh-postgres
  #   networks:
  #     - fullstackNetwork

volumes:
  api:
  database_postgres:
networks:
  fullstackNetwork:
    driver: bridge
